# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field


class CarSpecification(Item):
    rating = Field()
    reviews_count = Field()
    brand = Field()
    model = Field()
    generation = Field()
    body_type = Field()
    engine_type = Field()
    modification = Field()
    engine_volume = Field()
    fuel_type = Field()
    engine_power = Field()
    wheel_drive = Field()
    transmission_type = Field()
    acceleration = Field()
    fuel_consumption = Field()
    brand_country = Field()
    grade = Field()
    doors_count = Field()
    seats_count = Field()
    length = Field()
    width = Field()
    height = Field()
    wheel_base = Field()
    clearance = Field()
    front_track_width = Field()
    rear_track_width = Field()
    wheel_size = Field()
    trunk_capacity = Field()
    fuel_tank_capacity = Field()
    curb_weight = Field()
    total_weight = Field()
    gears_count = Field()
    front_suspension_type = Field()
    rear_suspension_type = Field()
    front_brake_type = Field()
    rear_brake_type = Field()
    max_speed = Field()
    eco_class = Field()
    engine_layout = Field()
    boost_type = Field()
    torque = Field()
    cylinders_layout = Field()
    cylinders_count = Field()
    valves_per_cylinder = Field()
    compression_ratio = Field()
    cylinder_spec = Field()
